name: dartkart

description: >
   dartkart is a framwork for web cartografy in the tradition of the
   JavaScript libraries OpenLayers and Leaflet. It is neither a 1:1 port of
   them nor does it provide the full functionality of either of them,
   but it has a similar structure and borrows a lot of ideas from them.

version: 0.0.3

authors:
  - Karl Guggisberg <karl.guggisberg@guggis.ch>

dependencies:
   browser: 0.3.7+6
   meta: 0.3.7+6
   unittest: 0.3.7+6
   args: 0.4.0