name: dartkart

description: >
   dartkart is a framwork for web cartografy in the tradition of the
   JavaScript libraries OpenLayers and Leaflet. It is neither a 1:1 port
   nor does it provide the full functionality of either of them,
   but it has a similar structure and borrows a lot of ideas from them.

version: 0.0.5+1

authors:
  - Karl Guggisberg <karl.guggisberg@guggis.ch>

dependencies:
   browser: 0.5.9
   meta: 0.5.9
   args: 0.5.9

dev_dependencies:
  unittest: 0.5.9
